### ISSUE TITLE
issue: Sharing & refreshing boards

### ISSUE THREAD

**Issue by ori-near** [near/devgigsboard-widgets#32]
**Current State:**
When a user clicks on [Boards](https://near.social/#/devgovgigs.near/widget/gigs-board.pages.Boards?nearDevGovGigsContractAccountId=devgovgigs.near), they see a list of tabs for various boards: MyNEARWallet Transition, near.social, Gigs Board, Funding ,etc. When they click on a specific board, such as Funding, the URL doesn't change. This creates a couple of problems:

1. The user cannot share a URL for a specific board 
2. The user cannot refresh the page and stay on the same board

**Desired State:**
1. A user should have the ability to get a specific URL for each board
2. When a user refreshes the page, they should stay on the board they were actively viewing instead of returning to the first

**Comment by nearmax** [comment]
There is a "link to the board" button and it seems to be working.

Btw, I have received the feedback that people think boards is a very important feature and they are looking for future improvements of it.

**Comment by frol** [comment]
While there is a "link to the board" button, I plan to fix this issue for the boards just like I have already done for the posts pages.

Thanks Ori for reporting it!

**Comment by ori-near** [comment]
To clarify – I meant a user cannot share the URL if they copy from their browser. But I do see the workaround with a link to this board. Thank you!
