### ISSUE TITLE
issue: Referral links stopped working

### ISSUE THREAD

**Issue by nearmax** [near/devgigsboard-widgets#39]
**To Reproduce**
1. Open any old referral link, e.g.: https://near.social/#/devgovgigs.near/widget/Ideas?referral=asdasd
2. Click "Create Idea";
3. Observe that `referral:asdasd` label is not pre-filled.

**Expected behavior**
`referral:asdasd` label is automatically pre-selected when creating a new post.

**Impact**
* Orgs that were approved for the referral program cannot start using it and they might even get upset if they notice that the posts coming from them are not attributed to their referral program anymore.

**Comment by frol** [comment]
Resolved in #40.

@nearmax Thanks for reporting it
