### ISSUE TITLE
Bug: Dev Gov Gigs Board showing up twice in the Applications section

### ISSUE THREAD

**Issue by ori-near** [near/devgigsboard-widgets#49]
**Describe the bug**
The NEAR Social applications browser section currently displays two Dev Gig Board applications, making it more confusing to find the official app. It seems like one of these apps is a test version that we are using for development purposes. And the other one is the real production gigs board.

**To Reproduce**
1. Go to https://near.social/#/
2. Under the Applications section, user sees two Developer Governance app icons:3. 
- First app leads to: https://near.social/#/bo.near/widget/gigs-board.pages.Feed
- Second app leads to: https://near.social/#/devgovgigs.near/widget/gigs-board.pages.Feed

**Expected behavior**
User should only see the official application, to ensure they can easily find the Gigs Board.

**Screenshots**
![Screen Shot 2023-03-07 at 5 51 35 PM](https://user-images.githubusercontent.com/110252255/223598775-623487c0-ff6b-4bb8-a31e-9c7985e543d7.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Safari
 - Version: Version 15.6.1 (17613.3.9.1.16)

**Comment by ailisp** [comment]
Fixed and checked in near.social website!
