### ISSUE TITLE
Create a dedicated community space (starting with Zero Knowledge)

### ISSUE THREAD

**Issue by ori-near** [near/devgigsboard-widgets#57]
### Problem
Currently, it is difficult for people who are interested in a particular topic area such as Zero Knowledge or Contract Standards to learn more about communities dedicated to that space. It is also difficult to sort through content on the Gigs Board around a particular topic. Lastly, there is no clear starting place to point people to who are interested in a particular topic from various content or marketing campaigns. As a result, community members have a hard time discovering, engaging with, and contributing to the ecosystem. 

### Solution
Introduce dedicated community spaces on the NEAR Developer Governance platform to bring together individuals, experts and organizations around various topics in one place. Each community will have a dedicated landing page with helpful content, including information about the community, its groups, conversations, events, and proposals. This will increase the visibility and reach of each community and make it easier for people to contribute.

For this MVP, we will create one community space for the Zero Knowledge community.

### Acceptance Criteria

**Community Page**
- Create a dedicated page for Zero Knowledge with discoverable URL slugs:
  - Homepage (overview tab): `/communities/zero-knowledge`
  - Every other tab: `/communities/zero-knowledge/posts`, `/communities/zero-knowledge/board`, `/communities/zero-knowledge/events`
  - A user should be able to access each one of these pages using the URL and stay on these pages when they click refresh
- The main header includes a breadcrumb navigation at the top: `Developer Governance / Communities / Zero Knowledge`
  - Developer Governance links to homepage
  - Communities will link to a separate All Communities page (will create in a separate ticket request)
  - Zero Knowledge will link to the main overview page
- The main header also includes a Title and Subtitle
  - Title: Community dame: `Zero Knowledge`
  - Subtitle: Community description `Building a Zero Knowledge ecosystem on NEAR.`
- The page includes a tabbed navigation
  - Current page link is bolded and underlined
- Mobile friendly

**Overview Tab**
- Should support markup language and display the copy from the attached reference design
- Editing capability: Admin should have the ability to edit the content (similar to other post types on the Gigs Board)

**Discussions Tab**
- Display the required labels message per the design
- Display the create panel from the homepage
  - When a user clicks on any create post type, the label field should get pre-populated with the `zero-knowledge` label 
- Display all posts with the zero-knowledge label

**Sponsorships Tab**
TBD

**Events Tab**
- Should support markup language and display the copy from the attached reference design
- Editing capability: Admin should have the ability to edit the content (similar to other post types on the Gigs Board)

### Reference Design
- [Figma mockups](https://www.figma.com/file/nCfirtyx3bgahewPVE1Yjn/Gigs-Board-Topics?node-id=0%3A1&t=UrYysAk5x2VHYiyo-1)

**Comment by frol** [comment]
@ailisp FYI, while we discussed it with Ori and Max, I was suggesting to use posts with dedicated `labels` to implement Communities:

* To list all the communities, just fetch the posts with `community` label, and link to the overview page `pages.Community?id=<post-id>`
* The community overview is just a post, so fetch it by ID, and display the post in the layout Ori designed
* The "Discussions" tab should be populated with the top-level posts with the same label as the community post (e.g. "Zero Knowledge" post will have two labels: `community` and `zero-knowledge`, so we should filter all the posts by `zero-knowledge` label)
* To implement "Events" tab I see two options:
  * I prefer this one: Define the template for the community overview post, where there will be basically just `# Events` section that will be split out on the "Overview" tab and displayed as the "Events" tab
  * Alternative: Search for another post that matches the `events` label and the `zero-knowledge` label (the label from the community overview post)

Notes:

* I believe it is fine, and even beneficial to display the `community` post on the home feed
* Re-using the posts, we allow incremental changes on the UI without a need to change the contract
* Re-using the posts, we don't need to implement new UI for editing the overview page, we just let edit the post as usual

**Comment by ailisp** [comment]
Done in #60
