### ISSUE TITLE
issue: Add keys to all maps and replace null with empty div

### ISSUE THREAD

**Issue by nearmax** [near/devgigsboard-widgets#6]
All maps implicit or explicit need to be using keys, see https://reactjs.org/docs/lists-and-keys.html Without it it produces weird hard to debug rendering bugs.

We should also replace all `null` and `""` in conditional statements with empty div, see https://github.com/near/devgigsboard-widgets/pull/5

**Comment by nearmax** [comment]
We actually need key on every div element https://t.me/NearSocialDev/1879

**Comment by frol** [comment]
Working on #24 I added the keys in quite a few places, but I will need to double-check it once again before closing this issue.

**Comment by frol** [comment]
I checked all the widgets, and confirm that `key` is properly set everywhere it is needed.
