### ISSUE TITLE
[Feed] Introduce search capability for posts

### ISSUE THREAD

**Issue by ori-near** [near/devgigsboard-widgets#66]
**Problem**
Currently, the Gigs Board only has a search by label function. Users are unable to search for posts using keyword, which makes it difficult to find relevant content.

**User Story**
As a Gigs Board user, I want to search for posts that mention a specific topic or keyword even if I don't know the exact phrasing or spelling. 

**Acceptance Criteria**
- Display a search input at the top of each page
- The search function uses fuzzy matching to return posts that match the search term, including partial matches and mispellings
- The search function is implemented using in-browser JavaScript to iterate through the post and do fuzzing matching instead of using middleware
- A UI element (e.g. spinning wheel) displays while the search is processing 
- The search function displays results as they are found, allowing users to see posts matching the search in real-time
- The search results should load quickly

**Note**
- This idea was featured as a bounty at the [ETH Denver Hackathon](https://www.ethdenver.com)

**Comment by ori-near** [comment]
@ailisp Estimates around 1-5 days of work, depending on whether the hackathon solution fully meet our acceptance criteria and production board needs. He will update the size once he get gets more information.

**Comment by ailisp** [comment]
Integration and made it works together with filter by labels was taking 1 day. Leaving another 2 days for addressing comments, possible optimizaations
