### ISSUE TITLE
feat: Remove collapsable comments

### ISSUE THREAD

**Issue by nearmax** [near/devgigsboard-widgets#8]
Right now we are loading all comments for all posts, but are also collapsing this by the default. This is done to not crowd the landing page.  However, it makes experience quite awkward. Instead we should do what Reddit is doing: the landing page posts should not have comments displayed and when the post card is clicked it opens the post with all comments expanded. The post with comments can open either in a new tab or as [a modal](https://getbootstrap.com/docs/5.3/components/modal/). This should also allow loading less content at once making it more responsive.

**Comment by frol** [comment]
With #24, an individual post page has all the nested posts expanded by default.
