### ISSUE TITLE
[Create Post] Improve reply to post UI experience

### ISSUE THREAD

**Issue by ori-near** [near/devgigsboard-widgets#89]
**Problem**
Currently, when a user clicks "reply" to a post, a dropdown menu of reply types appears without any explanation. This can lead to confusion and result in users selecting the wrong reply type.

![Image](https://user-images.githubusercontent.com/110252255/231027361-c9da88df-325a-4dc4-816f-0080ae8f8098.png)

**User Story**
As a user, when I click "reply" to a post, I want to see clear and digestible descriptions of each reply type so that I can select the appropriate option.

**Acceptance Criteria**
- The reply dialog box displays the five reply types with a clear icon, title, and description (see copy below)
- The dialog box is easy to dismiss and return to the original post

# Assets

## Images
Reply

![Image](https://user-images.githubusercontent.com/110252255/231029541-cb973160-3d57-46fb-9c2d-1b0815781349.png)

Hover State
![Image](https://user-images.githubusercontent.com/110252255/231029560-40867a9c-deb2-42e6-a975-cfb5ad3d978c.png)

## Copy

Idea
Get feedback from the community about a problem, opportunity, or need.

Solution
Provide a specific proposal or implementation to an idea, optionally requesting funding.

Attestation
Formally review or validate a solution as a recognized expert.

Sponsorship
Offer to fund projects, events, or proposals that match your needs.

Comment
Ask a question, provide information, or share a resource that is relevant to the thread.

**Comment by ori-near** [comment]
Hey @nearmax / @frol please review the suggested copy for the Reply UI experience and surface if you have any revisions or concerns.

**Comment by frol** [comment]
@ori-near Thanks Ori! The proposed solution looks great.

**Comment by ori-near** [comment]
@frol @nearmax NEARWEEK provided feedback that the "Attestation" term is not intuitive. Perhaps adding the definition addresses this problem. Should we go with something more simple such as "Formal Review"?
